<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>KartCityStudio.Common</RootNamespace>
        <AssemblyName>KartCityStudio.Common</AssemblyName>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <OutputPath>..\..\build\out\$(MSBuildProjectName)\Debug\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <OutputPath>..\..\build\out\$(MSBuildProjectName)\Release\</OutputPath>
      <DebugSymbols>true</DebugSymbols>
      <DebugType>embedded</DebugType>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\KartCity.Common\KartCity.Common.csproj" />
      <ProjectReference Include="..\KartriderLibrary\KartLibrary.csproj" />
      <ProjectReference Include="..\RaycityLibrary\RayCityLibrary.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Pfim" Version="0.11.3" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="System.Drawing.Common">
      </Reference>
    </ItemGroup>

</Project>
