<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>KartLibrary.Tests.Program</StartupObject>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <OutputPath>..\..\build\out\$(MSBuildProjectName)\Debug\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <OutputPath>..\..\build\out\$(MSBuildProjectName)\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.49-beta">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Pfim" Version="0.11.3" />
    <PackageReference Include="ReadLine" Version="2.0.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Veldrid" Version="4.9.0" />
    <PackageReference Include="Veldrid.ImGui" Version="5.89.2-ga121087cad" />
    <PackageReference Include="Veldrid.SDL2" Version="4.9.0" />
    <PackageReference Include="Veldrid.SPIRV" Version="1.0.15" />
    <PackageReference Include="Veldrid.StartupUtilities" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eP Library\eP Library.csproj" />
    <ProjectReference Include="..\KartriderLibrary\KartLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="libmatrixlib.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
