<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>25.3.31</Version>
        <Description>All common datatype between KartRider and Raycity.</Description>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <OutputPath>..\..\build\out\$(MSBuildProjectName)\Debug\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <OutputPath>..\..\build\out\$(MSBuildProjectName)\Release\</OutputPath>
      <DebugSymbols>true</DebugSymbols>
      <DebugType>embedded</DebugType>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\eP Library\eP Library.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="DotNetZip" Version="1.16.0" />
      <PackageReference Include="Veldrid" Version="4.9.0" />
    </ItemGroup>

</Project>
