<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Project">
    <OutputType>WinExe</OutputType>
    <GenerateProgramFile>false</GenerateProgramFile>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <OutputPath>..\..\..\build\out\KartCityStudio\$(MSBuildProjectName)\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <OutputPath>..\..\..\build\out\KartCityStudio\$(MSBuildProjectName)\Release\</OutputPath>
  </PropertyGroup>
  <ItemGroup Label="Project References">
    <ProjectReference Include="..\KartCityStudio.Game\KartCityStudio.Game.csproj" />
  </ItemGroup>
  <ItemGroup Label="Package References">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.0.0" />
  </ItemGroup>
  <ItemGroup>

  </ItemGroup>
</Project>
