<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>eP</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <OutputPath>..\..\build\out\eP Library\Debug\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <OutputPath>..\..\build\out\eP Library\Release\</OutputPath>
      <DebugSymbols>true</DebugSymbols>
      <DebugType>embedded</DebugType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ReadLine" Version="2.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Command\TelnetConsole.cs" />
      <None Include="Command\TelnetConsole.cs" />
    </ItemGroup>

</Project>
