<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <OutputPath>..\..\..\build\out\KartCityStudio\$(MSBuildProjectName)\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <OutputPath>..\..\..\build\out\KartCityStudio\$(MSBuildProjectName)\Release\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\KartCityStudioCommon\KartCityStudioCommon.csproj" />
    <ProjectReference Include="..\..\eP Library\eP Library.csproj" />
    <ProjectReference Include="..\..\KartCity.Common\KartCity.Common.csproj" />
    <ProjectReference Include="..\..\KartriderLibrary\KartLibrary.csproj">
      <Aliases></Aliases>
    </ProjectReference>
    <ProjectReference Include="..\..\RaycityLibrary\RayCityLibrary.csproj" />
    <ProjectReference Include="..\KartCityStudio.Resources\KartCityStudio.Resources.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ppy.osu.Framework" Version="2025.1121.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Platform\Windows\" />
  </ItemGroup>
</Project>
